services:
  web:
    build: .
    ports:
      - "5900:80"
    depends_on:
      - redis
    networks:
      - jenkins-network1
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - jenkins-network1
networks:
  jenkins-network:
    name: jenkins-network1
