auth_enabled: false
server:
  http_listen_port: 3100
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks
schema_config:
  configs:
    - from: 2025-07-15
      store: boltdb_shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
