{
 "title": "System Metric Dashboard",
 "time": { "from": "2025-07-15T12:21:30.533Z", "to": "2025-07-15T13:51:46.786Z" },
 "panels": [
  {
   "title": "System Uptime",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (Used Percentage)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O (Reads per Second)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 6 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"user\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}